version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: iot-nginx-proxy

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8876:80"
    environment:
      VIRTUAL_HOST: staging.iot.nik-web.ru
      VIRTUAL_PORT: 8876
    depends_on:
      - pgsql
    container_name: iot-backend-app

  pgsql:
    image: 'postgres:14'
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    container_name: iot-backend-db
