version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: iot-backend_nginx

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql
    container_name: iot-backend_app

  pgsql:
    image: 'postgres:14'
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    container_name: iot-backend_db
