<?php

namespace Tests;

use App\Models\AdmissionCommitteeContactsBlock;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        AdmissionCommitteeContactsBlock::factory()
                                       ->count(1)
                                       ->create();
    }
}
